networks:
  app_network:
    driver: bridge
    name: app_network

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}" ]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 10s
    networks:
      - app_network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - app_network

  api_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    container_name: api_test_container
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - app_network

  api_run:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: api_container
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9010:9010"
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - app_network