name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Make application-test.properties
      run: |
        cd ./api/src/main/resources
        touch ./application-api-test.properties
        echo "${{ secrets.PROPERTIES_TEST }}" > ./application-api-test.properties
        ls
      shell: bash

    - name: Run tests
      run: |
        ./gradlew clean -Dspring.profiles.active=test api:test 
        if [ $? -eq 0 ]; then
            echo "success"
          else
            echo "fail"
            exit 1
          fi
